<?php

/**
 * HOSTING CONFIGURATION APPLIER
 * ============================
 * 
 * This script applies the hosting configuration settings to your Laravel application.
 * Run this script after uploading to your hosting server and updating hosting-config.php
 * 
 * Usage: php apply-hosting-config.php
 */

// Load the hosting configuration
$hostingConfig = require_once __DIR__ . '/hosting-config.php';

// Path to the .env file
$envFile = __DIR__ . '/.env';

echo "Applying hosting configuration...\n";

// Create .env content based on hosting configuration
$debugValue = $hostingConfig['APP_DEBUG'] ? 'true' : 'false';
$sessionEncrypt = $hostingConfig['SESSION_ENCRYPT'] ? 'true' : 'false';
$allowStudentReg = $hostingConfig['ALLOW_STUDENT_REGISTRATION'] ? 'true' : 'false';
$allowCandidateReg = $hostingConfig['ALLOW_CANDIDATE_REGISTRATION'] ? 'true' : 'false';
$showResults = $hostingConfig['SHOW_RESULTS_IMMEDIATELY'] ? 'true' : 'false';
$currentDate = date('Y-m-d H:i:s');

// Handle optional configuration values
$logChannel = isset($hostingConfig['LOG_CHANNEL']) ? $hostingConfig['LOG_CHANNEL'] : 'stack';
$logLevel = isset($hostingConfig['LOG_LEVEL']) ? $hostingConfig['LOG_LEVEL'] : 'debug';
$awsAccessKey = isset($hostingConfig['AWS_ACCESS_KEY_ID']) ? $hostingConfig['AWS_ACCESS_KEY_ID'] : '';
$awsSecretKey = isset($hostingConfig['AWS_SECRET_ACCESS_KEY']) ? $hostingConfig['AWS_SECRET_ACCESS_KEY'] : '';
$awsRegion = isset($hostingConfig['AWS_DEFAULT_REGION']) ? $hostingConfig['AWS_DEFAULT_REGION'] : 'us-east-1';
$awsBucket = isset($hostingConfig['AWS_BUCKET']) ? $hostingConfig['AWS_BUCKET'] : '';

$envContent = <<<ENV
# Generated by hosting configuration applier
# Generated on: {$currentDate}

APP_NAME="{$hostingConfig['APP_NAME']}"
APP_ENV={$hostingConfig['APP_ENV']}
APP_KEY={$hostingConfig['APP_KEY']}
APP_DEBUG={$debugValue}
APP_TIMEZONE={$hostingConfig['APP_TIMEZONE']}
APP_URL={$hostingConfig['APP_URL']}

APP_LOCALE=en
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=en_US

APP_MAINTENANCE_DRIVER=file

PHP_CLI_SERVER_WORKERS=4

BCRYPT_ROUNDS=12

LOG_CHANNEL={$logChannel}
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL={$logLevel}

DB_CONNECTION={$hostingConfig['DB_CONNECTION']}
DB_HOST={$hostingConfig['DB_HOST']}
DB_PORT={$hostingConfig['DB_PORT']}
DB_DATABASE={$hostingConfig['DB_DATABASE']}
DB_USERNAME={$hostingConfig['DB_USERNAME']}
DB_PASSWORD={$hostingConfig['DB_PASSWORD']}

SESSION_DRIVER={$hostingConfig['SESSION_DRIVER']}
SESSION_LIFETIME={$hostingConfig['SESSION_LIFETIME']}
SESSION_ENCRYPT={$sessionEncrypt}
SESSION_PATH=/
SESSION_DOMAIN=null

BROADCAST_CONNECTION=log
FILESYSTEM_DISK={$hostingConfig['FILESYSTEM_DISK']}
QUEUE_CONNECTION={$hostingConfig['QUEUE_CONNECTION']}

CACHE_STORE={$hostingConfig['CACHE_STORE']}
CACHE_PREFIX=

MEMCACHED_HOST=127.0.0.1

REDIS_CLIENT=phpredis
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER={$hostingConfig['MAIL_MAILER']}
MAIL_HOST={$hostingConfig['MAIL_HOST']}
MAIL_PORT={$hostingConfig['MAIL_PORT']}
MAIL_USERNAME={$hostingConfig['MAIL_USERNAME']}
MAIL_PASSWORD="{$hostingConfig['MAIL_PASSWORD']}"
MAIL_ENCRYPTION={$hostingConfig['MAIL_ENCRYPTION']}
MAIL_FROM_ADDRESS={$hostingConfig['MAIL_FROM_ADDRESS']}
MAIL_FROM_NAME="{$hostingConfig['MAIL_FROM_NAME']}"

AWS_ACCESS_KEY_ID={$awsAccessKey}
AWS_SECRET_ACCESS_KEY={$awsSecretKey}
AWS_DEFAULT_REGION={$awsRegion}
AWS_BUCKET={$awsBucket}
AWS_USE_PATH_STYLE_ENDPOINT=false

VITE_APP_NAME="\${APP_NAME}"

# Voting System Specific Settings
ALLOW_STUDENT_REGISTRATION={$allowStudentReg}
ALLOW_CANDIDATE_REGISTRATION={$allowCandidateReg}
VOTING_SESSION_TIMEOUT={$hostingConfig['VOTING_SESSION_TIMEOUT']}
MAX_CANDIDATES_PER_POSITION={$hostingConfig['MAX_CANDIDATES_PER_POSITION']}
SHOW_RESULTS_IMMEDIATELY={$showResults}

ENV;

// Generate APP_KEY if not provided
if (empty($hostingConfig['APP_KEY']) || $hostingConfig['APP_KEY'] === 'base64:GENERATE_NEW_KEY_FOR_HOSTING') {
    $appKey = 'base64:' . base64_encode(random_bytes(32));
    $envContent = str_replace('APP_KEY=', 'APP_KEY=' . $appKey, $envContent);
    echo "✓ Generated new APP_KEY\n";
}

// Write the .env file
if (file_put_contents($envFile, $envContent) !== false) {
    echo "✓ .env file updated successfully\n";
} else {
    echo "✗ Failed to write .env file\n";
    exit(1);
}

// Apply PHP configuration if possible
if (function_exists('ini_set')) {
    ini_set('memory_limit', $hostingConfig['PHP_MEMORY_LIMIT']);
    ini_set('max_execution_time', $hostingConfig['PHP_MAX_EXECUTION_TIME']);
    ini_set('max_file_uploads', $hostingConfig['MAX_FILE_UPLOADS']);
    ini_set('upload_max_filesize', $hostingConfig['UPLOAD_MAX_FILESIZE']);
    ini_set('post_max_size', $hostingConfig['POST_MAX_SIZE']);
    echo "✓ PHP configuration applied\n";
}

// Check if directories exist and are writable
$directories = [
    'storage/logs',
    'storage/framework/cache',
    'storage/framework/sessions',
    'storage/framework/views',
    'bootstrap/cache'
];

foreach ($directories as $dir) {
    $path = __DIR__ . '/' . $dir;
    if (!is_dir($path)) {
        if (mkdir($path, 0755, true)) {
            echo "✓ Created directory: $dir\n";
        } else {
            echo "✗ Failed to create directory: $dir\n";
        }
    }
    
    if (!is_writable($path)) {
        if (chmod($path, 0755)) {
            echo "✓ Set permissions for: $dir\n";
        } else {
            echo "⚠ Warning: Could not set permissions for: $dir\n";
        }
    }
}

echo "\n";
echo "===========================================\n";
echo "HOSTING CONFIGURATION APPLIED SUCCESSFULLY\n";
echo "===========================================\n";
echo "\n";
echo "Next steps:\n";
echo "1. Run 'php artisan key:generate' to generate a new APP_KEY\n";
echo "2. Run 'php artisan migrate' to set up the database\n";
echo "3. Run 'php artisan config:cache' to optimize configuration\n";
echo "4. Run 'php artisan route:cache' to optimize routes\n";
echo "5. Run 'php artisan view:cache' to optimize views\n";
echo "6. Test your application thoroughly\n";
echo "\n";
echo "Important: Make sure to backup your database before running migrations!\n";
echo "\n";

// Display current configuration summary
echo "Current Configuration Summary:\n";
echo "-----------------------------\n";
echo "Environment: " . $hostingConfig['APP_ENV'] . "\n";
echo "Debug Mode: " . ($hostingConfig['APP_DEBUG'] ? 'Enabled' : 'Disabled') . "\n";
echo "App URL: " . $hostingConfig['APP_URL'] . "\n";
echo "Database: " . $hostingConfig['DB_DATABASE'] . " on " . $hostingConfig['DB_HOST'] . "\n";
echo "Mail From: " . $hostingConfig['MAIL_FROM_ADDRESS'] . "\n";
echo "Cache Store: " . $hostingConfig['CACHE_STORE'] . "\n";
echo "\n";