<?php

/**
 * SIMPLIFIED HOSTING SETUP
 * ========================
 * 
 * If you cannot run commands or use the main deployment scripts,
 * this script provides a minimal setup for hosting
 * 
 * Instructions:
 * 1. Update hosting-config.php with your hosting details
 * 2. Upload this file to your hosting
 * 3. Run: php simple-hosting-setup.php
 * 4. Or include this in any web-accessible page temporarily
 */

echo "🔧 Simple Hosting Setup\n";
echo "=======================\n\n";

// Check if hosting config exists
if (!file_exists(__DIR__ . '/hosting-config.php')) {
    die("❌ Error: hosting-config.php not found!\nPlease create this file with your hosting details.\n");
}

// Load hosting configuration
$config = require_once __DIR__ . '/hosting-config.php';

// Validate required settings
$required = ['APP_URL', 'DB_HOST', 'DB_DATABASE', 'DB_USERNAME'];
$missing = [];

foreach ($required as $key) {
    if (empty($config[$key]) || $config[$key] === 'your_database_name' || $config[$key] === 'yourdomain.com') {
        $missing[] = $key;
    }
}

if (!empty($missing)) {
    die("❌ Error: Please update these settings in hosting-config.php:\n" . implode(', ', $missing) . "\n");
}

echo "✅ Configuration validated\n";

// Create .env file
$envContent = "# Generated by simple hosting setup\n";
$envContent .= "# Generated on: " . date('Y-m-d H:i:s') . "\n\n";

$envContent .= "APP_NAME=\"{$config['APP_NAME']}\"\n";
$envContent .= "APP_ENV={$config['APP_ENV']}\n";
$envContent .= "APP_DEBUG=" . ($config['APP_DEBUG'] ? 'true' : 'false') . "\n";
$envContent .= "APP_TIMEZONE={$config['APP_TIMEZONE']}\n";
$envContent .= "APP_URL={$config['APP_URL']}\n";

// Generate APP_KEY if not provided
if (empty($config['APP_KEY'])) {
    $appKey = 'base64:' . base64_encode(random_bytes(32));
    $envContent .= "APP_KEY={$appKey}\n";
    echo "✅ Generated new APP_KEY\n";
} else {
    $envContent .= "APP_KEY={$config['APP_KEY']}\n";
}

$envContent .= "\n# Database Configuration\n";
$envContent .= "DB_CONNECTION={$config['DB_CONNECTION']}\n";
$envContent .= "DB_HOST={$config['DB_HOST']}\n";
$envContent .= "DB_PORT={$config['DB_PORT']}\n";
$envContent .= "DB_DATABASE={$config['DB_DATABASE']}\n";
$envContent .= "DB_USERNAME={$config['DB_USERNAME']}\n";
$envContent .= "DB_PASSWORD={$config['DB_PASSWORD']}\n";

$envContent .= "\n# Session Configuration\n";
$envContent .= "SESSION_DRIVER={$config['SESSION_DRIVER']}\n";
$envContent .= "SESSION_LIFETIME={$config['SESSION_LIFETIME']}\n";
$envContent .= "SESSION_ENCRYPT=" . ($config['SESSION_ENCRYPT'] ? 'true' : 'false') . "\n";

$envContent .= "\n# Cache and Queue\n";
$envContent .= "CACHE_STORE={$config['CACHE_STORE']}\n";
$envContent .= "QUEUE_CONNECTION={$config['QUEUE_CONNECTION']}\n";

$envContent .= "\n# Mail Configuration\n";
$envContent .= "MAIL_MAILER={$config['MAIL_MAILER']}\n";
$envContent .= "MAIL_HOST={$config['MAIL_HOST']}\n";
$envContent .= "MAIL_PORT={$config['MAIL_PORT']}\n";
$envContent .= "MAIL_USERNAME={$config['MAIL_USERNAME']}\n";
$envContent .= "MAIL_PASSWORD=\"{$config['MAIL_PASSWORD']}\"\n";
$envContent .= "MAIL_ENCRYPTION={$config['MAIL_ENCRYPTION']}\n";
$envContent .= "MAIL_FROM_ADDRESS={$config['MAIL_FROM_ADDRESS']}\n";
$envContent .= "MAIL_FROM_NAME=\"{$config['MAIL_FROM_NAME']}\"\n";

$envContent .= "\n# Other Settings\n";
$envContent .= "FILESYSTEM_DISK={$config['FILESYSTEM_DISK']}\n";
$envContent .= "LOG_CHANNEL=stack\n";
$envContent .= "LOG_LEVEL=error\n";

// Write .env file
if (file_put_contents(__DIR__ . '/.env', $envContent)) {
    echo "✅ .env file created\n";
} else {
    die("❌ Error: Could not create .env file\n");
}

// Create required directories
$directories = [
    'storage/logs',
    'storage/framework/cache',
    'storage/framework/sessions', 
    'storage/framework/views',
    'bootstrap/cache'
];

$created = 0;
foreach ($directories as $dir) {
    $path = __DIR__ . '/' . $dir;
    if (!is_dir($path)) {
        if (mkdir($path, 0755, true)) {
            $created++;
        }
    }
}

if ($created > 0) {
    echo "✅ Created $created directories\n";
}

// Test database connection
echo "🔍 Testing database connection...\n";
try {
    $pdo = new PDO(
        "mysql:host={$config['DB_HOST']};port={$config['DB_PORT']};dbname={$config['DB_DATABASE']}",
        $config['DB_USERNAME'],
        $config['DB_PASSWORD'],
        [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
    );
    echo "✅ Database connection successful\n";
    
    // Check for tables
    $stmt = $pdo->query("SHOW TABLES");
    $tables = $stmt->fetchAll(PDO::FETCH_COLUMN);
    echo "✅ Found " . count($tables) . " database tables\n";
    
} catch (PDOException $e) {
    echo "⚠️  Database connection failed: " . $e->getMessage() . "\n";
    echo "Please check your database credentials in hosting-config.php\n";
}

// Create basic .htaccess if it doesn't exist
$htaccessPath = __DIR__ . '/public/.htaccess';
if (!file_exists($htaccessPath)) {
    $htaccessContent = <<<HTACCESS
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>
HTACCESS;
    
    if (file_put_contents($htaccessPath, $htaccessContent)) {
        echo "✅ Created basic .htaccess file\n";
    }
}

echo "\n🎉 Simple hosting setup complete!\n";
echo "==================================\n";
echo "\nYour system should now be ready at: {$config['APP_URL']}\n";
echo "\nNext steps:\n";
echo "1. Test your application\n";
echo "2. Import database if needed\n";
echo "3. Delete this setup file for security\n";
echo "\n";

// Create summary file
$summary = [
    'setup_completed' => date('Y-m-d H:i:s'),
    'environment' => $config['APP_ENV'],
    'database' => $config['DB_DATABASE'],
    'app_url' => $config['APP_URL']
];

file_put_contents(__DIR__ . '/setup-summary.json', json_encode($summary, JSON_PRETTY_PRINT));

echo "📄 Setup summary saved to: setup-summary.json\n";
echo "\n";